api.sensor:
  path:     /sensor
  defaults: { _controller: 'Weather\ApiController::sensorAction' }

api.sensor.add:
  path:     /sensor/add
  defaults: { _controller: 'Weather\ApiController::sensorAddAction' }


api.temperature.new:
  path:     /temperature/new
  defaults: { _controller: 'Weather\ApiController::temperatureNewAction' }
  methods:  [POST]

api.pressure.new:
  path:     /pressure/new
  defaults: { _controller: 'Weather\ApiController::pressureNewAction' }
  methods:  [POST]

api.humidity.new:
  path:     /humidity/new
  defaults: { _controller: 'Weather\ApiController::humidityNewAction' }
  methods:  [POST]